# Generated by Django 2.0.1 on 2018-05-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
