# Generated by Django 2.0.1 on 2018-05-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0002_auto_20180509_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
