# Generated by Django 2.0.1 on 2018-05-16 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0005_qrcode_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
